### ISSUE TITLE
https://hokkien-writing.github.io/holodict contains 404 links

### ISSUE THREAD

**Issue by tddschn** [hokkien-writing/hokkien-writing.github.io#6]
`/holodict/*/` paths return 404 not found.

Example: 
- https://hokkien-writing.github.io/holodict/shenghuo/ (404)
- https://hokkien-writing.github.io/holodict/shenghuo (without the trailing slash, loads normalls)

The links on this page (https://hokkien-writing.github.io/holodict) all contain trailing slashes and lead visitors to 404 pages.

**Comment by hokkien-writing** [comment]
Remove the last slash `/` and it will be ok.

**Comment by hokkien-writing** [comment]
Issue confirmed, I will handle it soon

**Comment by tddschn** [comment]
Thank you!

If I may suggest, hosting the website on a service like Cloudflare Pages would be an easy fix since it automatically removes trailing slashes. :)

**Comment by hokkien-writing** [comment]
> Thank you!
> 
> 
> 
> If I may suggest, hosting the website on a service like Cloudflare Pages would be an easy fix since it automatically removes trailing slashes. :)

Good idea! 

We’ll explore Cloudflare Pages. It sounds like it’s not free 😬.

**Comment by hokkien-writing** [comment]
> `/holodict/*/` paths return 404 not found.
> 
> Example:
> 
> * https://hokkien-writing.github.io/holodict/shenghuo/ (404)
> * https://hokkien-writing.github.io/holodict/shenghuo (without the trailing slash, loads normalls)
> 
> The links on this page (https://hokkien-writing.github.io/holodict) all contain trailing slashes and lead visitors to 404 pages.

The problem is solved. Please try it again.
